export const SET_MAIN_ROUTE = 'SET_MAIN_ROUTE';
export const SET_SWITCH_ROUTE = 'SET_MAIN_ROUTE';

export const FETCH_DATA_REQUEST = 'FETCH_DATA_REQUEST';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAILURE = 'FETCH_DATA_FAILURE';

export const FETCH_STORES_REQUEST = 'FETCH_STORES_REQUEST';
export const FETCH_STORES_SUCCESS = 'FETCH_STORES_SUCCESS';
export const FETCH_STORES_FAILURE = 'FETCH_STORES_FAILURE';

export const JUST_STORE_UPDATED = 'JUST_STORE_UPDATED';

export const FETCH_DELETE_STORE_REQUEST = 'FETCH_DELETE_STORE_REQUEST';
export const FETCH_DELETE_STORE_SUCCESS = 'FETCH_DELETE_STORE_SUCCESS';
export const FETCH_DELETE_STORE_FAILURE = 'FETCH_DELETE_STORE_FAILURE';

export const SEARCH_ACTIVE_STORES = 'SEARCH_ACTIVE_STORES';

export const FETCH_PRODUCT_REQUEST = 'FETCH_PRODUCT_REQUEST';
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS';
export const FETCH_PRODUCT_FAILURE = 'FETCH_PRODUCT_FAILURE';

export const CHANGE_INDEX_OF_PRODUCT = 'CHANGE_INDEX_OF_PRODUCT';

export const FETCH_DEMO_PRODUCT_REQUEST = 'FETCH_DEMO_PRODUCT_REQUEST';
export const FETCH_DEMO_PRODUCT_SUCCESS = 'FETCH_DEMO_PRODUCT_SUCCESS';
export const FETCH_DEMO_PRODUCT_FAILURE = 'FETCH_DEMO_PRODUCT_FAILURE';

export const FETCH_NEW_ARRIVAL_PRODUCT_REQUEST =
  'FETCH_NEW_ARRIVAL_PRODUCT_REQUEST';
export const FETCH_NEW_ARRIVAL_PRODUCT_SUCCESS =
  'FETCH_NEW_ARRIVAL_PRODUCT_SUCCESS';
export const FETCH_NEW_ARRIVAL_PRODUCT_FAILURE =
  'FETCH_NEW_ARRIVAL_PRODUCT_FAILURE';

export const MODIFY_PRODUCT = 'MODIFY_PRODUCT';
export const LOAD_MORE_PRODUCTS = 'LOAD_MORE_PRODUCTS';
export const APPLY_FILTER_SORT = 'APPLY_FILTER_SORT';
export const APPLY_RESET_FILTER_SORT = 'APPLY_RESET_FILTER_SORT';
export const APPLY_PAGE = 'APPLY_PAGE';

export const MODIFY_DEMO_PRODUCT = 'const MODIFY_DEMO_PRODUCT';
export const MODIFY_FILTER_DEMO_PRODUCT = 'const MODIFY_FILTER_DEMO_PRODUCT';
export const MODIFY_ALL_DEMO_PRODUCT = 'const MODIFY_ALL_DEMO_PRODUCT';
export const LOAD_MORE_DEMO_PRODUCTS = 'const LOAD_MORE_DEMO_PRODUCTS';
export const APPLY_FILTER_SORT_DEMO = 'const APPLY_FILTER_SORT_DEMO';
export const APPLY_RESET_FILTER_SORT_PAGE_DEMO =
  'const APPLY_RESET_FILTER_SORT_PAGE_DEMO';

//MANUAL MODIFYING
export const MODIFY_FILTER_PRODUCT = 'MODIFY_FILTER_PRODUCT';
export const MODIFY_ALL_PRODUCT = 'MODIFY_ALL_PRODUCT';
export const MODIFY_NEW_ARRIVE_PRODUCT = 'MODIFY_NEW_ARRIVE_PRODUCT';
export const MODIFY_CART_DETAIL = 'MODIFY_CART_DETAIL';
export const MODIFY_PROFILE = 'MODIFY_PROFILE';

export const FETCH_CATEGORY_REQUEST = 'FETCH_CATEGORY_REQUEST';
export const FETCH_CATEGORY_SUCCESS = 'FETCH_CATEGORY_SUCCESS';
export const FETCH_CATEGORY_FAILURE = 'FETCH_CATEGORY_FAILURE';

export const FETCH_EDIT_PROFILE_REQUEST = 'FETCH_EDIT_PROFILE_REQUEST';
export const FETCH_EDIT_PROFILE_SUCCESS = 'FETCH_EDIT_PROFILE_SUCCESS';
export const FETCH_EDIT_PROFILE_FAILURE = 'FETCH_EDIT_PROFILE_FAILURE';

export const FETCH_PROFILE_DATA_REQUEST = 'FETCH_PROFILE_DATA_REQUEST';
export const FETCH_PROFILE_DATA_SUCCESS = 'FETCH_PROFILE_DATA_SUCCESS';
export const FETCH_PROFILE_DATA_FAILURE = 'FETCH_PROFILE_DATA_FAILURE';

export const FETCH_UPLOAD_PROFILE_IMAGE_REQUEST =
  'FETCH_UPLOAD_PROFILE_IMAGE_REQUEST';
export const FETCH_UPLOAD_PROFILE_IMAGE_SUCCESS =
  'FETCH_UPLOAD_PROFILE_IMAGE_SUCCESS';
export const FETCH_UPLOAD_PROFILE_IMAGE_FAILURE =
  'FETCH_UPLOAD_PROFILE_IMAGE_FAILURE';

export const FETCH_WISHLIST_REQUEST = 'FETCH_WISHLIST_REQUEST';
export const FETCH_WISHLIST_SUCCESS = 'FETCH_WISHLIST_SUCCESS';
export const FETCH_WISHLIST_FAILURE = 'FETCH_WISHLIST_FAILURE';

export const FILTER_SEARCH_WISHLIST = 'FILTER_SEARCH_WISHLIST';

export const FETCH_NOTIFICATION_REQUEST = 'FETCH_NOTIFICATION_REQUEST';
export const FETCH_NOTIFICATION_SUCCESS = 'FETCH_NOTIFICATION_SUCCESS';
export const FETCH_NOTIFICATION_FAILURE = 'FETCH_NOTIFICATION_FAILURE';

export const FETCH_MUTE_NOTIFICATION_REQUEST =
  'FETCH_MUTE_NOTIFICATION_REQUEST';
export const FETCH_MUTE_NOTIFICATION_SUCCESS =
  'FETCH_MUTE_NOTIFICATION_SUCCESS';
export const FETCH_MUTE_NOTIFICATION_FAILURE =
  'FETCH_MUTE_NOTIFICATION_FAILURE';

export const FETCH_HOME_DATA_REQUEST = 'FETCH_HOME_DATA_REQUEST';
export const FETCH_HOME_DATA_SUCCESS = 'FETCH_HOME_DATA_SUCCESS';
export const FETCH_HOME_DATA_FAILURE = 'FETCH_HOME_DATA_FAILURE';

export const FETCH_DEMO_DATA_REQUEST = 'FETCH_DEMO_DATA_REQUEST';
export const FETCH_DEMO_DATA_SUCCESS = 'FETCH_DEMO_DATA_SUCCESS';
export const FETCH_DEMO_DATA_FAILURE = 'FETCH_DEMO_DATA_FAILURE';

export const FETCH_ORDER_REQUEST = 'FETCH_ORDER_REQUEST';
export const FETCH_ORDER_SUCCESS = 'FETCH_ORDER_SUCCESS';
export const FETCH_ORDER_FAILURE = 'FETCH_ORDER_FAILURE';

export const NETWORK_FAILED = 'NETWORK_FAILED';

// actions/cartActions.js
export const addToCart = product => ({
  type: 'ADD_TO_CART',
  payload: product,
});

export const removeFromCart = product => ({
  type: 'REMOVE_FROM_CART',
  payload: product,
});
