export const BOOTSTRAP_AUTH = 'BOOTSTRAP_AUTH';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const SET_APP_FLOW = 'SET_APP_FLOW';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTRATION_COMPLETED = 'REGISTRATION_COMPLETED';
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';

